import { INodeProperties } from 'n8n-workflow';

export const sepaPaymentOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['sepaPayment'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a SEPA payment', description: 'Create a new SEPA payment' },
			{ name: 'Delete', value: 'delete', action: 'Delete a SEPA payment', description: 'Delete a SEPA payment by ID' },
			{ name: 'Get', value: 'get', action: 'Get a SEPA payment', description: 'Get a SEPA payment by ID' },
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many SEPA payments',
				description: 'Get a list of SEPA payments',
			},
			{ name: 'Update', value: 'update', action: 'Update a SEPA payment', description: 'Update a SEPA payment by ID' },
		],
		default: 'getAll',
	},
];

export const sepaPaymentFields: INodeProperties[] = [
	{
		displayName: 'SEPA Payment Name or ID',
		name: 'id',
		type: 'options',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['get', 'delete', 'update'] } },
		default: '',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'loadSepaPaymentOptions',
		},
		description:
			'ID of the SEPA payment. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Document Name or ID',
		name: 'documentId',
		type: 'options',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'loadDocumentOptions',
		},
		description:
			'ID of the document. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Debitor Name',
		name: 'debitorName',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'Name of the debitor',
	},
	{
		displayName: 'Debitor IBAN',
		name: 'debitorIban',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'IBAN of the debitor',
	},
	{
		displayName: 'Mandate ID',
		name: 'mandateId',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
	},
	{
		displayName: 'Mandate Date of Signature',
		name: 'mandateDateOfSignature',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'YYYY-MM-DD',
	},
	{
		displayName: 'Local Instrument',
		name: 'localInstrument',
		type: 'options',
		options: [
			{ name: 'B2B', value: 'B2B' },
			{ name: 'COR1', value: 'COR1' },
			{ name: 'CORE', value: 'CORE' },
		],
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: 'CORE',
		required: true,
		description: 'The local instrument for the SEPA payment',
	},
	{
		displayName: 'Sequence Type',
		name: 'sequenceType',
		type: 'options',
		options: [
			{ name: 'FNAL', value: 'FNAL' },
			{ name: 'FRST', value: 'FRST' },
			{ name: 'OOFF', value: 'OOFF' },
			{ name: 'RCUR', value: 'RCUR' },
		],
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: 'FRST',
		required: true,
		description: 'The sequence type of the SEPA payment',
	},
	{
		displayName: 'Amount (Cents)',
		name: 'amount',
		type: 'number',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: 0,
		required: true,
		description: 'The amount in cents',
	},
	{
		displayName: 'Reference',
		name: 'reference',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'The payment reference',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['create', 'update'] } },
		description: 'Additional fields for the SEPA payment',
		options: [
			{ name: 'Credit', value: 'CREDIT' },
			{
				displayName: 'Creditor BIC',
				name: 'creditor_bic',
				type: 'string',
				default: '',
				description: 'BIC of the creditor',
			},
			{
				displayName: 'Creditor IBAN',
				name: 'creditor_iban',
				type: 'string',
				default: '',
				description: 'IBAN of the creditor',
			},
			{
				displayName: 'Creditor Name',
				name: 'creditor_name',
				type: 'string',
				default: '',
				description: 'Name of the creditor',
			},
			{
				displayName: 'Debitor BIC',
				name: 'debitor_bic',
				type: 'string',
				default: '',
				description: 'BIC of the debitor',
			},
			{
				displayName: 'Remittance Information',
				name: 'remittance_information',
				type: 'string',
				default: '',
				description: 'Remittance information for the payment',
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				options: [
					{ name: 'Debit', value: 'DEBIT' },
					{ name: 'Credit', value: 'CREDIT' },
				],
				default: 'DEBIT',
				description: 'The type of the payment',
			},
		],
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['getAll'] } },
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Document ID Filter',
		name: 'documentIdFilter',
		type: 'string',
		displayOptions: { show: { resource: ['sepaPayment'], operation: ['getAll'] } },
		default: '',
		description: 'Filter by document ID',
	},
];
