import { INodeProperties } from 'n8n-workflow';

export const webHookOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['webHook'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a webhook', description: 'Create a new webhook' },
			{ name: 'Delete', value: 'delete', action: 'Delete a webhook', description: 'Delete a webhook by ID' },
			{ name: 'Get', value: 'get', action: 'Get a webhook', description: 'Get a webhook by ID' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many webhooks', description: 'Get a list of webhooks' },
			{ name: 'Update', value: 'update', action: 'Update a webhook', description: 'Update a webhook by ID' },
		],
		default: 'getAll',
	},
];

export const webHookFields: INodeProperties[] = [
	{
		displayName: 'WebHook Name or ID',
		name: 'id',
		type: 'options',
		displayOptions: { show: { resource: ['webHook'], operation: ['get', 'delete', 'update'] } },
		default: '',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'loadWebHookOptions',
		},
		description:
			'ID of the webhook. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'The URL to send the webhook to',
	},
	{
		displayName: 'Content Type',
		name: 'contentType',
		type: 'options',
		options: [
			{ name: 'Form', value: 'form' },
			{ name: 'JSON', value: 'json' },
		],
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: 'json',
		required: true,
		description: 'The content type of the webhook payload',
	},
	{
		displayName: 'Events',
		name: 'events',
		type: 'multiOptions',
		options: [
			{ name: 'contact.create', value: 'contact.create' },
			{ name: 'contact.delete', value: 'contact.delete' },
			{ name: 'contact.update', value: 'contact.update' },
			{ name: 'customer.create', value: 'customer.create' },
			{ name: 'customer.delete', value: 'customer.delete' },
			{ name: 'customer.update', value: 'customer.update' },
			{ name: 'document.completed', value: 'document.completed' },
			{ name: 'document.create', value: 'document.create' },
			{ name: 'document.deleted', value: 'document.deleted' },
			{ name: 'document.payment_add', value: 'document.payment_add' },
			{ name: 'document.payment_delete', value: 'document.payment_delete' },
			{ name: 'document.update', value: 'document.update' },
			{ name: 'position.create', value: 'position.create' },
			{ name: 'position.delete', value: 'position.delete' },
			{ name: 'position.update', value: 'position.update' },
			{ name: 'postbox.create', value: 'postbox.create' },
			{ name: 'postbox.delete', value: 'postbox.delete' },
			{ name: 'postbox.sent', value: 'postbox.sent' },
			{ name: 'postbox.update', value: 'postbox.update' },
		],
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: [],
		required: true,
		description: 'The events that will trigger the webhook',
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: '',
		required: true,
		description: 'A description for the webhook',
	},
	{
		displayName: 'Secret',
		name: 'secret',
		type: 'string',
		typeOptions: { password: true },
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: '',
		description: 'A secret to verify the webhook payload',
	},
	{
		displayName: 'Is Active',
		name: 'isActive',
		type: 'boolean',
		displayOptions: { show: { resource: ['webHook'], operation: ['create', 'update'] } },
		default: true,
		description: 'Whether the webhook is active',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		displayOptions: { show: { resource: ['webHook'], operation: ['getAll'] } },
		default: 50,
		description: 'Max number of results to return',
	},
];
