import { INodeProperties } from 'n8n-workflow';

export const customerOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['customer'],
			},
		},
		options: [
			{ name: 'Create', value: 'create', action: 'Create a customer', description: 'Create a new customer' },
			{ name: 'Delete', value: 'delete', action: 'Delete a customer', description: 'Delete a customer by ID' },
			{ name: 'Get', value: 'get', action: 'Get a customer', description: 'Get a customer by ID' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many customers', description: 'Get a list of customers' },
			{ name: 'Update', value: 'update', action: 'Update a customer', description: 'Update a customer by ID' },
		],
		default: 'getAll',
	},
];

export const customerFields: INodeProperties[] = [
	// ID parameter
	{
		displayName: 'Customer Name or ID',
		name: 'id',
		type: 'options',
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['get', 'delete', 'update'],
			},
		},
		default: '',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'loadCustomerOptions',
		},
		description:
			'ID of the customer. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	// Create/Update Required Fields
	{
		displayName: 'Last Name',
		name: 'lastName',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['create', 'update'],
			},
		},
		default: '',
		required: true,
		description: 'The last name of the customer',
	},
	{
		displayName: 'Company Name',
		name: 'companyName',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['create', 'update'],
			},
		},
		default: '',
		required: true,
		description: 'The company name of the customer',
	},
	// Additional Fields
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['create', 'update'],
			},
		},
		description: 'Additional fields for the customer',
		options: [
			{
				displayName: 'Acquire Options',
				name: 'acquire_options',
				type: 'options',
				default: undefined,
				description: 'Specifies how the customer was acquired',
				options: [
					{ name: 'Empfehlung Eines Anderen Kunden', value: 1 },
					{ name: 'Zeitungsanzeige', value: 2 },
					{ name: 'Eigene Akquisition', value: 3 },
					{ name: 'Mitarbeiter Akquisition', value: 4 },
					{ name: 'Google', value: 5 },
					{ name: 'Gelbe Seiten', value: 6 },
					{ name: 'Kostenlose Internet Plattform', value: 7 },
					{ name: 'Bezahlte Internet Plattform', value: 8 },
				],
			},
			{
				displayName: 'Additional Groups IDs',
				name: 'additional_groups_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list of additional customer group IDs',
			},
			{
				displayName: 'Archived',
				name: 'archived',
				type: 'boolean',
				default: false,
				description: 'Whether the customer is archived',
			},
			{
				displayName: 'Bank Account',
				name: 'bank_account',
				type: 'string',
				default: '',
				description: 'Bank account number of the customer',
			},
			{
				displayName: 'Bank Account Owner',
				name: 'bank_account_owner',
				type: 'string',
				default: '',
				description: 'Name of the bank account owner',
			},
			{
				displayName: 'Bank BIC',
				name: 'bank_bic',
				type: 'string',
				default: '',
				description: 'BIC of the customer’s bank',
			},
			{
				displayName: 'Bank Code',
				name: 'bank_code',
				type: 'string',
				default: '',
				description: 'Bank code (BLZ)',
			},
			{
				displayName: 'Bank IBAN',
				name: 'bank_iban',
				type: 'string',
				default: '',
				description: 'IBAN of the bank account',
			},
			{
				displayName: 'Bank Name',
				name: 'bank_name',
				type: 'string',
				default: '',
				description: 'Name of the bank',
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'string',
				default: '',
				description: 'Birth date of the customer (YYYY-MM-DD)',
			},
			{
				displayName: 'Buyer Reference',
				name: 'buyer_reference',
				type: 'string',
				default: '',
				description: 'Buyer reference used in ZUGFeRD or XRechnung documents',
			},
			{
				displayName: 'Cash Allowance (%)',
				name: 'cash_allowance',
				type: 'number',
				default: undefined,
				typeOptions: { minValue: 0, maxValue: 100 },
				description: 'Cash allowance percentage',
			},
			{
				displayName: 'Cash Allowance Days',
				name: 'cash_allowance_days',
				type: 'number',
				default: 7,
				description: 'Number of days the cash allowance is valid',
			},
			{
				displayName: 'Cash Discount',
				name: 'cash_discount',
				type: 'number',
				default: undefined,
				description: 'Cash discount value',
			},
			{
				displayName: 'Cash Discount Type',
				name: 'cash_discount_type',
				type: 'options',
				default: undefined,
				description: 'Defines whether the cash discount is a percentage or fixed amount',
				options: [
					{ name: 'Percent', value: 'PERCENT' },
					{ name: 'Amount', value: 'AMOUNT' },
				],
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				description: 'City of the customer',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: 'DE',
				description: 'Country of the customer',
			},
			{
				displayName: 'Court',
				name: 'court',
				type: 'string',
				default: '',
				description: 'Register court of the company',
			},
			{
				displayName: 'Court Registry Number',
				name: 'court_registry_number',
				type: 'string',
				default: '',
				description: 'Commercial register number',
			},
			{
				displayName: 'Delivery City',
				name: 'delivery_city',
				type: 'string',
				default: '',
				description: 'City of the delivery address',
			},
			{
				displayName: 'Delivery Company Name',
				name: 'delivery_company_name',
				type: 'string',
				default: '',
				description: 'Company name of the delivery address',
			},
			{
				displayName: 'Delivery Country',
				name: 'delivery_country',
				type: 'string',
				default: '',
				description: 'Country of the delivery address',
			},
			{
				displayName: 'Delivery First Name',
				name: 'delivery_first_name',
				type: 'string',
				default: '',
				description: 'First name of the delivery contact',
			},
			{
				displayName: 'Delivery Last Name',
				name: 'delivery_last_name',
				type: 'string',
				default: '',
				description: 'Last name of the delivery contact',
			},
			{
				displayName: 'Delivery Personal',
				name: 'delivery_personal',
				type: 'boolean',
				default: false,
				description: 'Whether the delivery address is personal',
			},
			{
				displayName: 'Delivery Salutation',
				name: 'delivery_salutation',
				type: 'options',
				default: 0,
				description:
					'Salutation for the delivery address. Example: 0 = nothing, 1 = Mr, 2 = Mrs, 3 = Company, 4 = Mr & Mrs, 5 = Married couple, 6 = Family.',
				options: [
					{ name: 'Empty', value: 0 },
					{ name: 'Mr', value: 1 },
					{ name: 'Mrs', value: 2 },
					{ name: 'Company', value: 3 },
					{ name: 'Mr & Mrs', value: 4 },
					{ name: 'Married Couple', value: 5 },
					{ name: 'Family', value: 6 },
				],
			},
			{
				displayName: 'Delivery State',
				name: 'delivery_state',
				type: 'string',
				default: '',
				description: 'State or region of the delivery address',
			},
			{
				displayName: 'Delivery Street',
				name: 'delivery_street',
				type: 'string',
				default: '',
				description: 'Street of the delivery address',
			},
			{
				displayName: 'Delivery Suffix 1',
				name: 'delivery_suffix_1',
				type: 'string',
				default: '',
				description: 'Additional delivery address information (suffix 1)',
			},
			{
				displayName: 'Delivery Suffix 2',
				name: 'delivery_suffix_2',
				type: 'string',
				default: '',
				description: 'Additional delivery address information (suffix 2)',
			},
			{
				displayName: 'Delivery Title',
				name: 'delivery_title',
				type: 'string',
				default: '',
				description: 'Academic or professional title of the delivery contact',
			},
			{
				displayName: 'Delivery Zip Code',
				name: 'delivery_zip_code',
				type: 'string',
				default: '',
				description: 'ZIP or postal code of the delivery address',
			},
			{
				displayName: 'Document PDF Type',
				name: 'document_pdf_type',
				type: 'options',
				default: 'default',
				description: 'Defines the PDF format used when sending documents',
				options: [
					{ name: 'Default', value: 'default' },
					{ name: 'XRechnung 2.1', value: 'xrechnung2_1_xml' },
					{ name: 'XRechnung 2.2', value: 'xrechnung2_2_xml' },
					{ name: 'XRechnung 2.3', value: 'xrechnung2_3_xml' },
					{ name: 'XRechnung 3.0', value: 'xrechnung3_0_xml' },
					{ name: 'ZUGFeRD 1', value: 'zugferd1' },
					{ name: 'ZUGFeRD 2.2', value: 'zugferd2_2' },
				],
			},
			{
				displayName: 'Due in Days',
				name: 'due_in_days',
				type: 'number',
				default: undefined,
				description: 'Number of days until payment is due',
			},
			{
				displayName: 'Email',
				name: 'emails',
				type: 'string',
				default: '',
				description: 'Comma-separated list of email addresses',
			},
			{
				displayName: 'Fax',
				name: 'fax',
				type: 'string',
				default: '',
				description: 'Fax number of the customer',
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: 'First name of the customer',
			},
			{
				displayName: 'Foreign Supplier Number',
				name: 'foreign_supplier_number',
				type: 'string',
				default: '',
				description: 'Supplier number assigned by the customer',
			},
			{
				displayName: 'Grace Period',
				name: 'grace_period',
				type: 'number',
				default: undefined,
				description: 'Grace period in days (deprecated, use Due in Days)',
			},
			{
				displayName: 'Group ID',
				name: 'group_id',
				type: 'string',
				default: '',
				description: 'Primary customer group ID',
			},
			{
				displayName: 'Info 1',
				name: 'info_1',
				type: 'string',
				default: '',
				description: 'Custom information field 1',
			},
			{
				displayName: 'Info 2',
				name: 'info_2',
				type: 'string',
				default: '',
				description: 'Custom information field 2',
			},
			{
				displayName: 'Internet',
				name: 'internet',
				type: 'string',
				default: '',
				description: 'Website URL of the customer',
			},
			{
				displayName: 'Login ID',
				name: 'login_id',
				type: 'number',
				default: undefined,
				description: 'Associated login ID',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				description: 'Mobile phone number of the customer',
			},
			{
				displayName: 'Note',
				name: 'note',
				type: 'string',
				default: '',
				description: 'Internal note about the customer',
			},
			{
				displayName: 'Number',
				name: 'number',
				type: 'string',
				default: '',
				description: 'Customer number (auto-generated if empty)',
			},
			{
				displayName: 'Payment Options',
				name: 'payment_options',
				type: 'options',
				default: undefined,
				description: 'Payment behavior rating of the customer',
				options: [
					{ name: 'Always on Time', value: 1 },
					{ name: 'Mostly on Time', value: 2 },
					{ name: 'Mostly Late', value: 3 },
					{ name: 'Always Late', value: 5 },
				],
			},
			{
				displayName: 'Personal',
				name: 'personal',
				type: 'boolean',
				default: false,
				description: 'Whether the customer is a private person',
			},
			{
				displayName: 'Phone 1',
				name: 'phone_1',
				type: 'string',
				default: '',
				description: 'Primary phone number',
			},
			{
				displayName: 'Phone 2',
				name: 'phone_2',
				type: 'string',
				default: '',
				description: 'Secondary phone number',
			},
			{
				displayName: 'Postbox',
				name: 'postbox',
				type: 'string',
				default: '',
				description: 'Postbox address',
			},
			{
				displayName: 'Postbox City',
				name: 'postbox_city',
				type: 'string',
				default: '',
				description: 'City of the postbox',
			},
			{
				displayName: 'Postbox Country',
				name: 'postbox_country',
				type: 'string',
				default: '',
				description: 'Country of the postbox',
			},
			{
				displayName: 'Postbox State',
				name: 'postbox_state',
				type: 'string',
				default: '',
				description: 'State of the postbox',
			},
			{
				displayName: 'Postbox Zip Code',
				name: 'postbox_zip_code',
				type: 'string',
				default: '',
				description: 'ZIP or postal code of the postbox',
			},
			{
				displayName: 'Sale Price Level',
				name: 'sale_price_level',
				type: 'options',
				default: undefined,
				description: 'Assigned sale price level for the customer',
				options: [
					{ name: 'SALEPRICE10', value: 'SALEPRICE10' },
					{ name: 'SALEPRICE2', value: 'SALEPRICE2' },
					{ name: 'SALEPRICE3', value: 'SALEPRICE3' },
					{ name: 'SALEPRICE4', value: 'SALEPRICE4' },
					{ name: 'SALEPRICE5', value: 'SALEPRICE5' },
					{ name: 'SALEPRICE6', value: 'SALEPRICE6' },
					{ name: 'SALEPRICE7', value: 'SALEPRICE7' },
					{ name: 'SALEPRICE8', value: 'SALEPRICE8' },
					{ name: 'SALEPRICE9', value: 'SALEPRICE9' },
				],
			},
			{
				displayName: 'Salutation',
				name: 'salutation',
				type: 'number',
				default: 0,
				description:
					'Salutation of the customer. Example: 0 = nothing, 1 = Mr, 2 = Mrs, 3 = Company, 4 = Mr & Mrs, 5 = Married couple, 6 = Family.',
			},
			{
				displayName: 'SEPA Agreement',
				name: 'sepa_agreement',
				type: 'options',
				default: undefined,
				description: 'SEPA mandate agreement type',
				options: [
					{ name: 'Basic', value: 'BASIC' },
					{ name: 'COR1 (Deprecated)', value: 'COR1' },
					{ name: 'Company', value: 'COMPANY' },
					{ name: 'None', value: 'NULL' },
				],
			},
			{
				displayName: 'SEPA Agreement Date',
				name: 'sepa_agreement_date',
				type: 'string',
				default: '',
				description: 'Date of the SEPA agreement (YYYY-MM-DD)',
			},
			{
				displayName: 'SEPA Mandate Reference',
				name: 'sepa_mandate_reference',
				type: 'string',
				default: '',
				description: 'SEPA mandate reference identifier',
			},
			{
				displayName: 'Since Date',
				name: 'since_date',
				type: 'string',
				default: '',
				description: 'Customer since date (YYYY-MM-DD)',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				description: 'State or region of the customer',
			},
			{
				displayName: 'Street',
				name: 'street',
				type: 'string',
				default: '',
				description: 'Street address of the customer',
			},
			{
				displayName: 'Suffix 1',
				name: 'suffix_1',
				type: 'string',
				default: '',
				description: 'Additional address information (suffix 1)',
			},
			{
				displayName: 'Suffix 2',
				name: 'suffix_2',
				type: 'string',
				default: '',
				description: 'Additional address information (suffix 2)',
			},
			{
				displayName: 'Supplier Number',
				name: 'supplier_number',
				type: 'string',
				default: '',
				description: 'Supplier number assigned by the system',
			},
			{
				displayName: 'Tax Number',
				name: 'tax_number',
				type: 'string',
				default: '',
				description: 'Tax number of the customer',
			},
			{
				displayName: 'Tax Options',
				name: 'tax_options',
				type: 'options',
				default: undefined,
				description: 'Tax handling option for the customer',
				options: [
					{ name: 'Ausfuhrlieferung', value: 'AL' },
					{ name: 'Innergemeinschaftliche Lieferung', value: 'IG' },
					{ name: 'Nicht Steuerbar (Drittland)', value: 'nStb' },
					{ name: 'Nicht Steuerbar (EU Mit VAT ID)', value: 'nStbUstID' },
					{ name: 'Nicht Steuerbar (EU without VAT ID)', value: 'nStbNoneUstID' },
					{ name: 'Nicht Steuerbar Import', value: 'nStbIm' },
					{ name: 'Other Tax Exemption', value: 'sStfr' },
					{ name: 'Reverse Charge (§13b)', value: 'revc' },
					{ name: 'Umsatzsteuerpflichtig', value: 'NULL' },
				],
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: 'Academic or professional title of the customer',
			},
			{
				displayName: 'VAT Identifier',
				name: 'vat_identifier',
				type: 'string',
				default: '',
				description: 'VAT identification number',
			},
			{
				displayName: 'Zip Code',
				name: 'zip_code',
				type: 'string',
				default: '',
				description: 'ZIP or postal code of the customer',
			},
		],
	},
	// Get All Filters
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['getAll'],
			},
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['customer'],
				operation: ['getAll'],
			},
		},
		description: 'Filters to apply to the customer list',
		options: [
			{
				displayName: 'Company Name',
				name: 'company_name',
				type: 'string',
				default: '',
				description: 'Filter by company name',
			},
			{ displayName: 'Email', name: 'emails', type: 'string', default: '', description: 'Filter by email' },
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: 'Filter by first name',
			},
			{ displayName: 'Group ID', name: 'group_id', type: 'string', default: '', description: 'Filter by group ID' },
			{ displayName: 'Last Name', name: 'last_name', type: 'string', default: '', description: 'Filter by last name' },
			{ displayName: 'Number', name: 'number', type: 'string', default: '', description: 'Filter by customer number' },
			{ displayName: 'Zip Code', name: 'zip_code', type: 'string', default: '', description: 'Filter by zip code' },
		],
	},
];
